<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260116150919 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE link (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(64) NOT NULL, password_hash VARCHAR(255) DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, max_downloads INT DEFAULT NULL, download_count INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, permission_level VARCHAR(255) NOT NULL, node_id INT NOT NULL, creator_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_36AC99F15F37A13B ON link (token)');
        $this->addSql('CREATE INDEX IDX_36AC99F1460D9FD7 ON link (node_id)');
        $this->addSql('CREATE INDEX IDX_36AC99F161220EA6 ON link (creator_id)');
        $this->addSql('CREATE TABLE link_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, session_token VARCHAR(255) NOT NULL, ip_address VARCHAR(255) NOT NULL, user_agent VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at VARCHAR(255) NOT NULL, link_id INT NOT NULL, connected_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AD228F21ADA40271 ON link_session (link_id)');
        $this->addSql('CREATE INDEX IDX_AD228F21349E946C ON link_session (connected_user_id)');
        $this->addSql('CREATE TABLE node (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, size BIGINT DEFAULT NULL, extension VARCHAR(255) DEFAULT NULL, mimetype VARCHAR(255) DEFAULT NULL, storage_path VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, parent_id INT DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_857FE845727ACA70 ON node (parent_id)');
        $this->addSql('CREATE INDEX IDX_857FE8457E3C61F9 ON node (owner_id)');
        $this->addSql('CREATE TABLE node_permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, accepted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notification_sent BOOLEAN NOT NULL, permission_level VARCHAR(255) NOT NULL, node_id INT NOT NULL, target_user_id INT NOT NULL, shared_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_34E91D40460D9FD7 ON node_permission (node_id)');
        $this->addSql('CREATE INDEX IDX_34E91D406C066AFE ON node_permission (target_user_id)');
        $this->addSql('CREATE INDEX IDX_34E91D405489CD19 ON node_permission (shared_by_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, avatar VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F1460D9FD7 FOREIGN KEY (node_id) REFERENCES node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE link ADD CONSTRAINT FK_36AC99F161220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE link_session ADD CONSTRAINT FK_AD228F21ADA40271 FOREIGN KEY (link_id) REFERENCES link (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE link_session ADD CONSTRAINT FK_AD228F21349E946C FOREIGN KEY (connected_user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE node ADD CONSTRAINT FK_857FE845727ACA70 FOREIGN KEY (parent_id) REFERENCES node (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE node ADD CONSTRAINT FK_857FE8457E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE node_permission ADD CONSTRAINT FK_34E91D40460D9FD7 FOREIGN KEY (node_id) REFERENCES node (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE node_permission ADD CONSTRAINT FK_34E91D406C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE node_permission ADD CONSTRAINT FK_34E91D405489CD19 FOREIGN KEY (shared_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE link DROP CONSTRAINT FK_36AC99F1460D9FD7');
        $this->addSql('ALTER TABLE link DROP CONSTRAINT FK_36AC99F161220EA6');
        $this->addSql('ALTER TABLE link_session DROP CONSTRAINT FK_AD228F21ADA40271');
        $this->addSql('ALTER TABLE link_session DROP CONSTRAINT FK_AD228F21349E946C');
        $this->addSql('ALTER TABLE node DROP CONSTRAINT FK_857FE845727ACA70');
        $this->addSql('ALTER TABLE node DROP CONSTRAINT FK_857FE8457E3C61F9');
        $this->addSql('ALTER TABLE node_permission DROP CONSTRAINT FK_34E91D40460D9FD7');
        $this->addSql('ALTER TABLE node_permission DROP CONSTRAINT FK_34E91D406C066AFE');
        $this->addSql('ALTER TABLE node_permission DROP CONSTRAINT FK_34E91D405489CD19');
        $this->addSql('DROP TABLE link');
        $this->addSql('DROP TABLE link_session');
        $this->addSql('DROP TABLE node');
        $this->addSql('DROP TABLE node_permission');
        $this->addSql('DROP TABLE "user"');
    }
}
